Add -DBUILD_TESTING=OFF to disable tests
PLSysSec/rlbox_sandboxing_api pull request #31
Opened 2021-07-31 08:00 UTC by bansan85

and Catch2 dependency.

Fix #28

There is no need to update CI. Tests are always enabled by default.

I also add a minor documentation about `make install`. I don't think it mandatory to a message about the empty `make` when tests are disabled.

2021-11-16 00:06 UTC, shravanrn commented
> 
> 
> Polite ping ❤️ 😃

Terribly sorry about the long delay. I will definitely review the PR this week :)

2021-11-16 00:49 UTC, shravanrn requested changes
Could we also rebase once (sorry for the churn). If you can address the docs related comment below, I can merge this assuming it works on Linux (its ok if the DBUILD_TESTING=OFF doesn't work on windows for now)

2021-11-16 00:49 UTC, shravanrn commented on README.md
> +3. Disable tests
Yup, can we make this a top level section please?

2021-11-16 00:49 UTC, shravanrn commented on CMakeLists.txt
> +if(BUILD_TESTING)
This still seems to build tests on windows even when using -DBUILD_TESTING=OFF 

```
cmake -S . -B .\build -DBUILD_TESTING=OFF
cmake --build .\build --parallel
```

2021-11-23 17:38 UTC, shravanrn commented
@bansan85 I pushed a rebased commit implementing this in the tree

2021-11-23 17:38 UTC, closed without merging

2021-11-23 22:05 UTC, bansan85 commented
Thanks for rebased my commit :) I'm in a rush in my personal time. I didn't write a single line of code for a week :/